version: '3.8'

include:
  # Creates a standard Postgress instance
  - ps-postgres.yaml

  # Creates the internal MongoDB replica set
  - ps-mongo.yaml

services:
  # Main PowerSync service
  powersync:
    image: container-registry.staging.journeyapps.com/powersync-service:0.0.1
    # TODO improve this with an internal CLI
    command: ['node', 'powersync-service/lib/unified.js']
    environment:
      # TODO use a default value via CLI
      POWERSYNC_CONFIG: /config/powersync.yml
    volumes:
      # Mounts the specified config folder to the container
      - ./config:/config
    ports:
      # TODO match with config yaml file if changed
      - 8080:8080

  # An example demo app which is linked to the PowerSync instance above
  demo:
    build:
      context: ./demo-launcher
      dockerfile: Dockerfile
      args:
        POWERSYNC_PORT: 8080
    ports:
      - 3030:3000
