version: '3.8'

services:
  # MongoDB Service used internally
  mongo:
    image: mongo:5.0
    command: --replSet rs0 --bind_ip_all
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongo_storage:/data/db

  # Initializes the MongoDB replica set. This service will not usually be actively running
  mongo-rs-init:
    image: mongo:5.0
    depends_on:
      - mongo
    restart: 'no'
    entrypoint:
      - bash
      - -c
      #  TODO neaten this
      - 'sleep 10 && mongo --host mongo:27017 --eval ''rs.initiate({_id: "rs0", version: 1, members: [{ _id: 0, host : "mongo:27017" }]})'''

volumes:
  mongo_storage:
